/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.LoginForm;

import DAO.AccountDAO;
import DAO.AccountRoleDAO;
import java.awt.Color;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JOptionPane;
import model.Account;
import model.AccountRole;

/**
 *
 * @author ME1
 */
public class JFrLogin extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public JFrLogin() {
       
        initComponents();
         
        txtusername.setBackground(new java.awt.Color(0,0,0,1));
        txtpassword.setBackground(new java.awt.Color(0,0,0,1));
    }
    private Account getAccount() throws SQLException{
        
        AccountDAO adao = new AccountDAO();
        String name = this.txtusername.getText().trim();
        String pass = this.txtpassword.getText().trim();
        
        
        
        Account acc = adao.getAccountByUsername(name);
        return acc;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        lbTitle = new javax.swing.JLabel();
        lbUserName = new javax.swing.JLabel();
        txtusername = new javax.swing.JTextField();
        lbUnderLineUser = new javax.swing.JLabel();
        lbIconUser = new javax.swing.JLabel();
        lbPass = new javax.swing.JLabel();
        txtpassword = new javax.swing.JPasswordField();
        lbUnderLinePass = new javax.swing.JLabel();
        lbIconDisable = new javax.swing.JLabel();
        lbIconShow = new javax.swing.JLabel();
        ckbRemember = new javax.swing.JCheckBox();
        btnLogin = new javax.swing.JButton();
        lblErrUsername = new javax.swing.JLabel();
        lblErrPassWord = new javax.swing.JLabel();
        lblClose = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(102, 204, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbTitle.setFont(new java.awt.Font("Segoe UI", 0, 32)); // NOI18N
        lbTitle.setForeground(new java.awt.Color(255, 255, 255));
        lbTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTitle.setText("Đăng nhập");
        jPanel2.add(lbTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 47, 420, -1));

        lbUserName.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lbUserName.setForeground(new java.awt.Color(255, 255, 255));
        lbUserName.setText("Tên đăng nhập");
        jPanel2.add(lbUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 341, -1));

        txtusername.setFont(txtusername.getFont().deriveFont(txtusername.getFont().getSize()+2f));
        txtusername.setForeground(new java.awt.Color(255, 255, 255));
        txtusername.setBorder(null);
        txtusername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtusernameActionPerformed(evt);
            }
        });
        jPanel2.add(txtusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 150, 240, 20));

        lbUnderLineUser.setForeground(new java.awt.Color(255, 255, 255));
        lbUnderLineUser.setText("_________________________________________");
        jPanel2.add(lbUnderLineUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 290, -1));

        lbIconUser.setBackground(new java.awt.Color(0, 0, 0));
        lbIconUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbIconUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icon/icons8_user_20px_1.png"))); // NOI18N
        jPanel2.add(lbIconUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(335, 147, 40, 39));

        lbPass.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lbPass.setForeground(new java.awt.Color(255, 255, 255));
        lbPass.setText("Mật khẩu");
        jPanel2.add(lbPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 341, -1));

        txtpassword.setFont(txtpassword.getFont().deriveFont(txtpassword.getFont().getSize()+2f));
        txtpassword.setForeground(new java.awt.Color(255, 255, 255));
        txtpassword.setBorder(null);
        txtpassword.setCaretColor(new java.awt.Color(255, 255, 255));
        jPanel2.add(txtpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 240, 20));

        lbUnderLinePass.setForeground(new java.awt.Color(255, 255, 255));
        lbUnderLinePass.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbUnderLinePass.setText("_________________________________________");
        lbUnderLinePass.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel2.add(lbUnderLinePass, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 290, 20));

        lbIconDisable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbIconDisable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icon/icons8_invisible_20px_1.png"))); // NOI18N
        lbIconDisable.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbIconDisable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbIconDisableMouseClicked(evt);
            }
        });
        jPanel2.add(lbIconDisable, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 220, 30, 40));

        lbIconShow.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbIconShow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icon/icons8_eye_20px_1.png"))); // NOI18N
        lbIconShow.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbIconShow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbIconShowMouseClicked(evt);
            }
        });
        jPanel2.add(lbIconShow, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 220, 30, 40));

        ckbRemember.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        ckbRemember.setForeground(new java.awt.Color(255, 255, 255));
        ckbRemember.setText("Nhớ mật khẩu?");
        ckbRemember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckbRememberActionPerformed(evt);
            }
        });
        jPanel2.add(ckbRemember, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, -1, -1));

        btnLogin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(25, 118, 211));
        btnLogin.setText("Đăng nhập");
        btnLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        jPanel2.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 341, 40));
        jPanel2.add(lblErrUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));
        jPanel2.add(lblErrPassWord, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 240, -1));

        lblClose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icon/Close Window_3.png"))); // NOI18N
        lblClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCloseMouseClicked(evt);
            }
        });
        jPanel2.add(lblClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, 30, 20));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 440));

        setSize(new java.awt.Dimension(407, 438));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lbIconDisableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbIconDisableMouseClicked
        txtpassword.setEchoChar((char)0);
        lbIconDisable.setVisible(false);
        lbIconDisable.setEnabled(false);
        lbIconShow.setEnabled(true);
        lbIconShow.setEnabled(true);
    }//GEN-LAST:event_lbIconDisableMouseClicked

    private void lbIconShowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbIconShowMouseClicked
        txtpassword.setEchoChar((char)8226);
        lbIconDisable.setVisible(true);
        lbIconDisable.setEnabled(true);
        lbIconShow.setEnabled(false);
        lbIconShow.setEnabled(false);
    }//GEN-LAST:event_lbIconShowMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        for (double i = 0.0; i <=1.0; i = i+0.1){
            String val = i+ "";
            float f = Float.valueOf(val);
            this.setOpacity(f);
            try{
                Thread.sleep(50);
            }catch(Exception e){
                
            }
        }
    }//GEN-LAST:event_formWindowOpened

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        try {
            if(this.txtusername.getText().equals("")){
                this.lblErrUsername.setText("Không để trống username");
                this.lblErrUsername.setForeground(Color.red);
            }else if(!this.txtusername.getText().equals("")){
                this.lblErrUsername.setText("");
            }
            
            if(String.valueOf(this.txtpassword.getPassword()).equals("")){
                this.lblErrPassWord.setText("Không để trống username");
                this.lblErrPassWord.setForeground(Color.red);
            }else if(!String.valueOf(this.txtpassword.getPassword()).equals("")){
                this.lblErrPassWord.setText("");
            }
            
          AccountRole role =  AccountRoleDAO.getById(getAccount().getUsername());
          
      
        } catch (SQLException ex) {
            Logger.getLogger(JFrLogin.class.getName()).log(Level.SEVERE, null, ex);
        }

        
    }//GEN-LAST:event_btnLoginActionPerformed

    private void txtusernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtusernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtusernameActionPerformed

    private void ckbRememberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckbRememberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ckbRememberActionPerformed

    private void btnCloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseExited
        
    }//GEN-LAST:event_btnCloseMouseExited

    private void btnCloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseEntered
       

    }//GEN-LAST:event_btnCloseMouseEntered

    private void btnCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseClicked
     
    }//GEN-LAST:event_btnCloseMouseClicked

    private void lblCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseClicked
       int check = JOptionPane.showConfirmDialog(this, "Bạn có muốn thoát không?");
       if(check ==0){
           System.exit(0);
       }
    }//GEN-LAST:event_lblCloseMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JCheckBox ckbRemember;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbIconDisable;
    private javax.swing.JLabel lbIconShow;
    private javax.swing.JLabel lbIconUser;
    private javax.swing.JLabel lbPass;
    private javax.swing.JLabel lbTitle;
    private javax.swing.JLabel lbUnderLinePass;
    private javax.swing.JLabel lbUnderLineUser;
    private javax.swing.JLabel lbUserName;
    private javax.swing.JLabel lblClose;
    private javax.swing.JLabel lblErrPassWord;
    private javax.swing.JLabel lblErrUsername;
    private javax.swing.JPasswordField txtpassword;
    private javax.swing.JTextField txtusername;
    // End of variables declaration//GEN-END:variables
}
